parameters:
    jdr.mailer.templating.class: JDR\MailerBundle\Template\TemplatingEngine
    jdr.mailer.part_resolver_registry.class: JDR\Mailer\PartResolverRegistry
    jdr.mailer.email_builder.class: JDR\Mailer\EmailBuilder
    jdr.mailer.swift.class: JDR\MailerSwiftMailerBridge\SwiftMailer

services:
    jdr.mailer.templating:
        class: "%jdr.mailer.templating.class%"
        arguments:
            - "@templating"

    jdr.mailer.part_resolver_registry:
        class: "%jdr.mailer.part_resolver_registry.class%"
        private: true

    jdr.mailer.email_builder:
        class: "%jdr.mailer.email_builder.class%"
        private: true
        arguments:
            - "@jdr.mailer.part_resolver_registry"

    jdr.mailer.swift:
        class: "%jdr.mailer.swift.class%"
        private: true
        arguments:
            - "@mailer"
            - "@jdr.mailer.email_builder"

    jdr.mailer:
        alias: jdr.mailer.swift
